// Generated by gencpp from file ur_msgs/EndPoseResponse.msg
// DO NOT EDIT!


#ifndef UR_MSGS_MESSAGE_ENDPOSERESPONSE_H
#define UR_MSGS_MESSAGE_ENDPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace ur_msgs
{
template <class ContainerAllocator>
struct EndPoseResponse_
{
  typedef EndPoseResponse_<ContainerAllocator> Type;

  EndPoseResponse_()
    : eef_pose()  {
    }
  EndPoseResponse_(const ContainerAllocator& _alloc)
    : eef_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _eef_pose_type;
  _eef_pose_type eef_pose;





  typedef boost::shared_ptr< ::ur_msgs::EndPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur_msgs::EndPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EndPoseResponse_

typedef ::ur_msgs::EndPoseResponse_<std::allocator<void> > EndPoseResponse;

typedef boost::shared_ptr< ::ur_msgs::EndPoseResponse > EndPoseResponsePtr;
typedef boost::shared_ptr< ::ur_msgs::EndPoseResponse const> EndPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur_msgs::EndPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur_msgs::EndPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ur_msgs': ['/home/dof6/catkin_ws/src/fmauch_universal_robot/ur_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur_msgs::EndPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_msgs::EndPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_msgs::EndPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_msgs::EndPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_msgs::EndPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_msgs::EndPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur_msgs::EndPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e78f5a947f0283d2ebd6c70bccbefe0";
  }

  static const char* value(const ::ur_msgs::EndPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e78f5a947f0283dULL;
  static const uint64_t static_value2 = 0x2ebd6c70bccbefe0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur_msgs::EndPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur_msgs/EndPoseResponse";
  }

  static const char* value(const ::ur_msgs::EndPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur_msgs::EndPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose eef_pose\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::ur_msgs::EndPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur_msgs::EndPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.eef_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EndPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur_msgs::EndPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur_msgs::EndPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "eef_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.eef_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR_MSGS_MESSAGE_ENDPOSERESPONSE_H
