// Generated by gencpp from file ur_msgs/EndPose.msg
// DO NOT EDIT!


#ifndef UR_MSGS_MESSAGE_ENDPOSE_H
#define UR_MSGS_MESSAGE_ENDPOSE_H

#include <ros/service_traits.h>


#include <ur_msgs/EndPoseRequest.h>
#include <ur_msgs/EndPoseResponse.h>


namespace ur_msgs
{

struct EndPose
{

typedef EndPoseRequest Request;
typedef EndPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EndPose
} // namespace ur_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_msgs::EndPose > {
  static const char* value()
  {
    return "1e78f5a947f0283d2ebd6c70bccbefe0";
  }

  static const char* value(const ::ur_msgs::EndPose&) { return value(); }
};

template<>
struct DataType< ::ur_msgs::EndPose > {
  static const char* value()
  {
    return "ur_msgs/EndPose";
  }

  static const char* value(const ::ur_msgs::EndPose&) { return value(); }
};


// service_traits::MD5Sum< ::ur_msgs::EndPoseRequest> should match 
// service_traits::MD5Sum< ::ur_msgs::EndPose > 
template<>
struct MD5Sum< ::ur_msgs::EndPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::EndPose >::value();
  }
  static const char* value(const ::ur_msgs::EndPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::EndPoseRequest> should match 
// service_traits::DataType< ::ur_msgs::EndPose > 
template<>
struct DataType< ::ur_msgs::EndPoseRequest>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::EndPose >::value();
  }
  static const char* value(const ::ur_msgs::EndPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_msgs::EndPoseResponse> should match 
// service_traits::MD5Sum< ::ur_msgs::EndPose > 
template<>
struct MD5Sum< ::ur_msgs::EndPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::EndPose >::value();
  }
  static const char* value(const ::ur_msgs::EndPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::EndPoseResponse> should match 
// service_traits::DataType< ::ur_msgs::EndPose > 
template<>
struct DataType< ::ur_msgs::EndPoseResponse>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::EndPose >::value();
  }
  static const char* value(const ::ur_msgs::EndPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_MSGS_MESSAGE_ENDPOSE_H
