// Generated by gencpp from file ur_msgs/JointStates.msg
// DO NOT EDIT!


#ifndef UR_MSGS_MESSAGE_JOINTSTATES_H
#define UR_MSGS_MESSAGE_JOINTSTATES_H

#include <ros/service_traits.h>


#include <ur_msgs/JointStatesRequest.h>
#include <ur_msgs/JointStatesResponse.h>


namespace ur_msgs
{

struct JointStates
{

typedef JointStatesRequest Request;
typedef JointStatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointStates
} // namespace ur_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_msgs::JointStates > {
  static const char* value()
  {
    return "5581a04fddc1f7d62a2958142211f72d";
  }

  static const char* value(const ::ur_msgs::JointStates&) { return value(); }
};

template<>
struct DataType< ::ur_msgs::JointStates > {
  static const char* value()
  {
    return "ur_msgs/JointStates";
  }

  static const char* value(const ::ur_msgs::JointStates&) { return value(); }
};


// service_traits::MD5Sum< ::ur_msgs::JointStatesRequest> should match 
// service_traits::MD5Sum< ::ur_msgs::JointStates > 
template<>
struct MD5Sum< ::ur_msgs::JointStatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::JointStates >::value();
  }
  static const char* value(const ::ur_msgs::JointStatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::JointStatesRequest> should match 
// service_traits::DataType< ::ur_msgs::JointStates > 
template<>
struct DataType< ::ur_msgs::JointStatesRequest>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::JointStates >::value();
  }
  static const char* value(const ::ur_msgs::JointStatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_msgs::JointStatesResponse> should match 
// service_traits::MD5Sum< ::ur_msgs::JointStates > 
template<>
struct MD5Sum< ::ur_msgs::JointStatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::JointStates >::value();
  }
  static const char* value(const ::ur_msgs::JointStatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::JointStatesResponse> should match 
// service_traits::DataType< ::ur_msgs::JointStates > 
template<>
struct DataType< ::ur_msgs::JointStatesResponse>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::JointStates >::value();
  }
  static const char* value(const ::ur_msgs::JointStatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_MSGS_MESSAGE_JOINTSTATES_H
