// Generated by gencpp from file ur_msgs/JointTrajectory.msg
// DO NOT EDIT!


#ifndef UR_MSGS_MESSAGE_JOINTTRAJECTORY_H
#define UR_MSGS_MESSAGE_JOINTTRAJECTORY_H

#include <ros/service_traits.h>


#include <ur_msgs/JointTrajectoryRequest.h>
#include <ur_msgs/JointTrajectoryResponse.h>


namespace ur_msgs
{

struct JointTrajectory
{

typedef JointTrajectoryRequest Request;
typedef JointTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointTrajectory
} // namespace ur_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_msgs::JointTrajectory > {
  static const char* value()
  {
    return "1373137967a4be74f31370fe945d1aee";
  }

  static const char* value(const ::ur_msgs::JointTrajectory&) { return value(); }
};

template<>
struct DataType< ::ur_msgs::JointTrajectory > {
  static const char* value()
  {
    return "ur_msgs/JointTrajectory";
  }

  static const char* value(const ::ur_msgs::JointTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::ur_msgs::JointTrajectoryRequest> should match 
// service_traits::MD5Sum< ::ur_msgs::JointTrajectory > 
template<>
struct MD5Sum< ::ur_msgs::JointTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::JointTrajectory >::value();
  }
  static const char* value(const ::ur_msgs::JointTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::JointTrajectoryRequest> should match 
// service_traits::DataType< ::ur_msgs::JointTrajectory > 
template<>
struct DataType< ::ur_msgs::JointTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::JointTrajectory >::value();
  }
  static const char* value(const ::ur_msgs::JointTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_msgs::JointTrajectoryResponse> should match 
// service_traits::MD5Sum< ::ur_msgs::JointTrajectory > 
template<>
struct MD5Sum< ::ur_msgs::JointTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::JointTrajectory >::value();
  }
  static const char* value(const ::ur_msgs::JointTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::JointTrajectoryResponse> should match 
// service_traits::DataType< ::ur_msgs::JointTrajectory > 
template<>
struct DataType< ::ur_msgs::JointTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::JointTrajectory >::value();
  }
  static const char* value(const ::ur_msgs::JointTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_MSGS_MESSAGE_JOINTTRAJECTORY_H
