// Generated by gencpp from file ur_msgs/JointTrajectoryRequest.msg
// DO NOT EDIT!


#ifndef UR_MSGS_MESSAGE_JOINTTRAJECTORYREQUEST_H
#define UR_MSGS_MESSAGE_JOINTTRAJECTORYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur_msgs
{
template <class ContainerAllocator>
struct JointTrajectoryRequest_
{
  typedef JointTrajectoryRequest_<ContainerAllocator> Type;

  JointTrajectoryRequest_()
    : arm_joint_name()
    , arm_qpos()
    , eef_pose()
    , eef_quat()
    , grasp(0.0)  {
    }
  JointTrajectoryRequest_(const ContainerAllocator& _alloc)
    : arm_joint_name(_alloc)
    , arm_qpos(_alloc)
    , eef_pose(_alloc)
    , eef_quat(_alloc)
    , grasp(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _arm_joint_name_type;
  _arm_joint_name_type arm_joint_name;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _arm_qpos_type;
  _arm_qpos_type arm_qpos;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _eef_pose_type;
  _eef_pose_type eef_pose;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _eef_quat_type;
  _eef_quat_type eef_quat;

   typedef double _grasp_type;
  _grasp_type grasp;





  typedef boost::shared_ptr< ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct JointTrajectoryRequest_

typedef ::ur_msgs::JointTrajectoryRequest_<std::allocator<void> > JointTrajectoryRequest;

typedef boost::shared_ptr< ::ur_msgs::JointTrajectoryRequest > JointTrajectoryRequestPtr;
typedef boost::shared_ptr< ::ur_msgs::JointTrajectoryRequest const> JointTrajectoryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ur_msgs': ['/home/dof6/catkin_ws/src/fmauch_universal_robot/ur_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11a12f53ad6d8c438206098e03d31517";
  }

  static const char* value(const ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11a12f53ad6d8c43ULL;
  static const uint64_t static_value2 = 0x8206098e03d31517ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur_msgs/JointTrajectoryRequest";
  }

  static const char* value(const ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string[] arm_joint_name\n\
float64[] arm_qpos\n\
float64[] eef_pose\n\
float64[] eef_quat\n\
float64 grasp\n\
";
  }

  static const char* value(const ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arm_joint_name);
      stream.next(m.arm_qpos);
      stream.next(m.eef_pose);
      stream.next(m.eef_quat);
      stream.next(m.grasp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointTrajectoryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur_msgs::JointTrajectoryRequest_<ContainerAllocator>& v)
  {
    s << indent << "arm_joint_name[]" << std::endl;
    for (size_t i = 0; i < v.arm_joint_name.size(); ++i)
    {
      s << indent << "  arm_joint_name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.arm_joint_name[i]);
    }
    s << indent << "arm_qpos[]" << std::endl;
    for (size_t i = 0; i < v.arm_qpos.size(); ++i)
    {
      s << indent << "  arm_qpos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.arm_qpos[i]);
    }
    s << indent << "eef_pose[]" << std::endl;
    for (size_t i = 0; i < v.eef_pose.size(); ++i)
    {
      s << indent << "  eef_pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.eef_pose[i]);
    }
    s << indent << "eef_quat[]" << std::endl;
    for (size_t i = 0; i < v.eef_quat.size(); ++i)
    {
      s << indent << "  eef_quat[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.eef_quat[i]);
    }
    s << indent << "grasp: ";
    Printer<double>::stream(s, indent + "  ", v.grasp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR_MSGS_MESSAGE_JOINTTRAJECTORYREQUEST_H
