// Generated by gencpp from file ur_msgs/JointStatesResponse.msg
// DO NOT EDIT!


#ifndef UR_MSGS_MESSAGE_JOINTSTATESRESPONSE_H
#define UR_MSGS_MESSAGE_JOINTSTATESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur_msgs
{
template <class ContainerAllocator>
struct JointStatesResponse_
{
  typedef JointStatesResponse_<ContainerAllocator> Type;

  JointStatesResponse_()
    : joint_states()  {
    }
  JointStatesResponse_(const ContainerAllocator& _alloc)
    : joint_states(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _joint_states_type;
  _joint_states_type joint_states;





  typedef boost::shared_ptr< ::ur_msgs::JointStatesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur_msgs::JointStatesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct JointStatesResponse_

typedef ::ur_msgs::JointStatesResponse_<std::allocator<void> > JointStatesResponse;

typedef boost::shared_ptr< ::ur_msgs::JointStatesResponse > JointStatesResponsePtr;
typedef boost::shared_ptr< ::ur_msgs::JointStatesResponse const> JointStatesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur_msgs::JointStatesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur_msgs::JointStatesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ur_msgs': ['/home/dof6/catkin_ws/src/fmauch_universal_robot/ur_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur_msgs::JointStatesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_msgs::JointStatesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_msgs::JointStatesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_msgs::JointStatesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_msgs::JointStatesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_msgs::JointStatesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur_msgs::JointStatesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5581a04fddc1f7d62a2958142211f72d";
  }

  static const char* value(const ::ur_msgs::JointStatesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5581a04fddc1f7d6ULL;
  static const uint64_t static_value2 = 0x2a2958142211f72dULL;
};

template<class ContainerAllocator>
struct DataType< ::ur_msgs::JointStatesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur_msgs/JointStatesResponse";
  }

  static const char* value(const ::ur_msgs::JointStatesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur_msgs::JointStatesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string joint_states\n\
\n\
";
  }

  static const char* value(const ::ur_msgs::JointStatesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur_msgs::JointStatesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointStatesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur_msgs::JointStatesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur_msgs::JointStatesResponse_<ContainerAllocator>& v)
  {
    s << indent << "joint_states: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joint_states);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR_MSGS_MESSAGE_JOINTSTATESRESPONSE_H
